### ISSUE TITLE
TTML2 is confusing

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml-webvtt-mapping#1]
Use of "TTML2" is doublely confusing - I understand the constraints are against IMSC1, and thus neither TTML2 nor TTML(1). Suggest removing "TTML2" and replace appropriate occurrences with "IMSC1".

(raised by Mike Dolan on 2015-09-18)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/415

**Comment by andreastai** [comment]
I have updated the document to change the name of the profile from "T2VP" to "TVTT". I have also removed any place where the numeral 2 was used as an abbreviation for the English word "to".
Courtney Kennedy, 18 Sep 2015

I updated the document to change the name of the defined profile from "T2VP" to "TVTT". In addition, I changed any places that used the numeral 2 as an abbreviation for the English word "to". The mapping document does not include "TTML2" anywhere within in it.
Courtney Kennedy, 18 Sep 2015

[nigel]: [meeting 2015-09-24] Numeral 2 removed from name of mapping profile to avoid confusion with TTML2. Profile is not based on IMSC 1 however note Issue-446 requests this.
24 Sep 2015

From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/415
