### ISSUE TITLE
Use gh-pages instead of master

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml-webvtt-mapping#19]
Any specific reason to use the master branch on github instead of gh-pages? Would be nice to have the editor's draft visible at http://w3c.github.io/ttml-webvtt-mapping/ .

**Comment by andreastai** [comment]
Thanks for the hint. I created gh-pages branch. I will leave the master branch for the time being becaust it has been published for a while already. I will sync master and gh-pages branch.

**Comment by nigelmegitt** [comment]
For this to work the main page needs to be called index.html - that's the page that gh-pages serves.

**Comment by plehegar** [comment]
Indeed, unless you guys are really into the Unicorn Toasters Markup API. :)

**Comment by andreastai** [comment]
Addressed with https://github.com/w3c/ttml-webvtt-mapping/commit/bc45f24676ad4f32845b800e570f44351996dc5a and https://github.com/w3c/ttml-webvtt-mapping/commit/a61f1ecf475c12f8192a21464ab7715343139213
