### ISSUE TITLE
Is the example conversion at "2.2.4.1.3 Time Expression" incorrect?

### ISSUE THREAD

**Issue by SnakeWhisperer** [w3c/ttml-webvtt-mapping#34]
Can someone explain the parameters and/or method used for the example conversion of **01:02:43:07** at **29.97 fps**? I'm getting a different value when converting.

The first example takes **01:02:43:07** at **30 fps** and gets **01:02:43.233** (3,763.233333 seconds), which is the same I get. However, for the second one, the document gets **01:02:43.234**, but I get the following:

<br>

### If non-drop frame is considered:

**01:02:43:07** => **112,897** frames

$$112,897 frames/(30000/1001) f/s = 3,766.996566 seconds$$

Which gives us **01:02:46.997**

<br><br>

### If drop frame is considered:

**01:02:43:07** => **112,897** counted frames => **112,785** rendered/scanned frames (112 frames have been dropped)

$$112,785 frames/(30000/1001) f/s = 3,763.2595 seconds$$

Which gives us **01:02:43.260**

**Comment by nigelmegitt** [comment]
The example does not say what the time base is: it could be media or SMPTE.

## SMPTE time base

The relevant method for SMPTE Time base is described in [TTML2 I.3 SMPTE Time Base](https://www.w3.org/TR/ttml2/#time-expression-semantics-smpte).

Here:

```
countedFrames = (3600 * hours + 60 * minutes + seconds) * frameRate + frames
              = (3600 * 1 + 60 * 2 + 43) * 30 + 7
              = 112,897
```

The document does not say, so let's assume that `dropMode="dropNTSC"` for the sake of the calculation. Then:

```
droppedFrames = (hours * 54 + minutes - floor(minutes/10)) * 2
              = (1 * 54 + 2 - floor(2/10)) * 2
              = 112
```

And

```
effectiveFrameRate = 30 * 1000 / 1001
                   = 29.97
```

Bringing it all together:

```
S = (countedFrames - droppedFrames + (subFrames / subFrameRate)) / effectiveFrameRate
  = (112897 - 112 + 0) / 29.97
  = 3763.263
```

which gives us **01:02:43.263** which is indeed different to the example!

## Media timebase

The relevant method for Media Time base is described in [TTML2 I.2.2 Relationship to Media Time](https://www.w3.org/TR/ttml2/#semantics-media-timing).

Here, dropMode is not used - by the way, this will be the same result in IMSC:

```
M = referenceBegin + 3600 * hours + 60 * minutes + seconds + ((frames + (subFrames / subFrameRate)) / effectiveFrameRate) 
  = 0 + 3600 * 1 + 60 * 2 + 43 + ((7 + 0) / 29.97)
  = 3764.2335669
  = 3764.234 (rounded to 3 d.p.)
```

which gives us the same result as in the document, **01:02:43.234**.

## Conclusion

The document's result is not wrong, but the assumptions made to reach the example conclusion are not explicitly listed, only implied by the notes after the examples (If the TTML document contains Time Base parameter equal to "smpte"), which suggest that other conditions were used, which can only realistically mean "media" timebase in the example.

**Comment by SnakeWhisperer** [comment]
Okay, this is perfect. I understand now. Thank you very much for such a detailed explanation and the references.
