### ISSUE TITLE
#time-clock is forbidden

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml-webvtt-mapping#5]
# time-clock is forbidden but time expressions of the form "hours: minutes: seconds.fractional-seconds" are allowed.

(raised by Pierre-Anthony Lemieux on 2015-09-23)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/437

**Comment by andreastai** [comment]
This is indeed an error and should be ammended. An action was opened for this.

Andreas Tai, 18 Oct 2015, 10:01:52
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/437
